### ISSUE TITLE
协方差矩阵

### ISSUE THREAD

**Issue by GoodStudy-DayUp** [tsyw/MachineLearningNotes#1]
想问下您，第一份PDF（1.Intro_Math.pdf，截图如下所示）中协方差不是对称么，为什么在这个公式中不是对称，而是转置呀，看B站上那个白板推导的视频也是转置，这里有点没太明白，希望能得到您的讲解，非常感谢！
![image](https://user-images.githubusercontent.com/65880866/89728494-49514580-da60-11ea-9fbc-fa949e213650.png)

**Comment by tsyw** [comment]
> 想问下您，第一份PDF（1.Intro_Math.pdf，截图如下所示）中协方差不是对称么，为什么在这个公式中不是对称，而是转置呀，看B站上那个白板推导的视频也是转置，这里有点没太明白，希望能得到您的讲解，非常感谢！
> ![image](https://user-images.githubusercontent.com/65880866/89728494-49514580-da60-11ea-9fbc-fa949e213650.png)

您好，不知道您有没有弄清楚，建议在看这些公式的时候，可以将矩阵元的下标（rowxcolum）一并写上，这样就可以看明白了。
